### ISSUE TITLE
[TODO] interact with wakatime-cli

### ISSUE THREAD

**Issue by miRoox** [miRoox/wolfram-wakatime#1]
TODO List: 

- [x] send heartbeat
- [x] get dashboard time
- [x] install cli if missing
- [ ] update cli if there is new version
- [ ] read API key from the configuration file.
- [ ] write API key to the configuration file.
- [ ] autoload WakaTime package.
